name: google_signin_example
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^1.1.2
  cached_network_image: ^2.0.0
  cloud_firestore: null
  cupertino_icons: ^1.0.0
  custom_switch: ^0.0.1
  firebase_auth: null
  firebase_core: ^0.4.5
  flutter_html: ^0.11.0
  fluttertoast: ^7.1.6
  font_awesome_flutter: ^8.10.0
  form_field_validator: ^1.0.1
  google_fonts: ^1.1.1
  google_sign_in: ^4.4.4
  html: null
  http: ^0.12.0+2
  intl: ^0.16.1
  lint: ^1.2.0
  provider: ^4.3.2+2
  receive_sharing_intent: ^1.4.2
  share: ^0.6.5+4
  shimmer: ^1.1.2
  url_launcher: null
  youtube_player_flutter: ^6.0.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/
